[[cv]]
name = "Programming Languages"
path = "Programming_Languages.html"

  [[cv.item]]
  	title="Java"
  	rank = 5
  	
  [[cv.item]]
  	title="C"
  	rank =4	
	
  [[cv.item]]
  	title="GoLang"
	rank=5
	
  [[cv.item]]
  	title="JavaScript"
	rank=4
	
  [[cv.item]]
  	title="Dart"
	rank= 3
	
  [[cv.item]]
   	title="Ruby"
	rank=3
	       
  [[cv.item]]
  	title="Python"
	rank=2
	 
  [[cv.item]]
    title="PHP"
	rank= 1
					 
	   
[[cv]]
name = "Operating Systems"
path = "Operating_Systems.html"
    
  [[cv.item]]
  	title="Linux"
  	rank = 5
 
  [[cv.item]]
  	title="FreeBsd"
  	rank = 3

  [[cv.item]]
  	title="Solaris"
  	rank = 2
	
  [[cv.item]]
  	title="Cisko IOS"
  	rank = 2

[[cv]]
name = "Data Bases"
path = "Data-bases.html"
  
  [[cv.item]]
  	title="Mysql"
  	rank = 5	

  [[cv.item]]
  	title="Redis"
  	rank = 4
  	
   [[cv.item]]
  	title="Sqlite"
  	rank = 3
  	
   [[cv.item]]
  	title="Postegress"
  	rank = 4	
  
   [[cv.item]]
  	title="Oracle"
  	rank = 2
  	
[[cv]]
name = "Telecommunication Application"
path = "Telecommunication-application.html"
  	
   [[cv.item]]
  	title="Asterisk"
  	rank = 5
  	
   [[cv.item]]
  	title="Kamailio"
  	rank = 3
  	
   [[cv.item]]
  	title="Cisko"
  	rank = 2
  	
   [[cv.item]]
  	title="Kannel"
  	rank = 4
  	
  	
[[cv]]
name = "WebApplication Development"
path = "WebApplication-development.html"
  	
   [[cv.item]]
  	title="Angularjs"
  	rank = 5
  	
   [[cv.item]]
  	title="Dart"
  	rank = 4
  	
   [[cv.item]]
  	title="Google Web Toolkit"
  	rank = 3
  	
   [[cv.item]]
  	title="Ruby on Rails"
  	rank = 3
  	
   [[cv.item]]
  	title="PHP"
  	rank = 2
  	
[[cv]]
name = "Coud Computing"
path = "Cloud-computing.html"

   [[cv.item]]
  	title="Digital Ocean"
  	rank = 5
  	
   [[cv.item]]
  	title="AWS"
  	rank = 5
  	
   [[cv.item]]
  	title="Rackspace"
  	rank = 4 	  	  	
  	 	   	  	 	 	  	
  	
  		 			
  