[[cv]]
name = "Programming Languages"
path = "Programming-languages.html"
img="assets/images/"

  [[cv.item]]
  	title="Java"
  	rank = 5
  	duration = 1
  	link =""
  	extra="in production"
  	img="assets/images/java.jpg" 
  	
  [[cv.item]]
  	title="C"
  	rank =4
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/c.png" 
  	
	
  [[cv.item]]
  	title="GoLang"
	rank=5
  	duration = 1
  	link =""		
  	extra="in production" 
  	img="assets/images/golang.png" 
  	
	
  [[cv.item]]
  	title="JavaScript"
	rank=4
  	duration = 1
  	link =""
  	extra="in production" 
  	img="assets/images/javascript.png" 
  	
  		
  [[cv.item]]
  	title="Dart"
	rank= 3
  	duration = 1
  	link =""
  	extra="in production" 
  	img="assets/images/dart.png" 
  	
  		
  [[cv.item]]
   	title="Ruby"
	rank=3
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/ruby.jpg" 
  	
	       
  [[cv.item]]
  	title="Python"
	rank=2
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/python.png" 
  	
  		 
  [[cv.item]]
    title="PHP"
	rank= 1
  	duration = 1
  	link =""					 
  	extra="in production" 
  	img="assets/images/php.png" 
  	
	   
[[cv]]
name = "Operating Systems"
path = "Operating-systems.html"
img="assets/images/"
    
  [[cv.item]]
  	title="Linux"
  	rank = 5
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/linux.png" 
  	
 
  [[cv.item]]
  	title="FreeBsd"
  	rank = 3
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/freebsd.png" 
  	
 
  [[cv.item]]
  	title="Solaris"
  	rank = 2
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/solaris.gif" 
  	
 	
  [[cv.item]]
  	title="Cisco IOS"
  	rank = 2
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/cisco.jpg" 
  	
 
[[cv]]
name = "Data Bases"
path = "Data-bases.html"
img="assets/images/"
  
  [[cv.item]]
  	title="Mysql"
  	rank = 5	
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/mysql.png" 
  	
 
  [[cv.item]]
  	title="Redis"
  	rank = 4
  	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/redis.png" 
  	
   	
   [[cv.item]]
  	title="Sqlite"
  	rank = 3
   	duration = 1
  	link =""	
  	extra="in production" 
  	img="assets/images/sqlite.png" 
  	
  	
   [[cv.item]]
  	title="Postgresql"
  	rank = 4
  	duration = 3
  	link =""	
  	extra="in production"  	
  	img="assets/images/postgresql.png" 
  	
  
   [[cv.item]]
  	title="Oracle"
  	rank = 2
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/oracle.png" 
  	
   	
[[cv]]
name = "Telecommunication Application"
path = "Telecommunication-application.html"
img="assets/images/"
  	
   [[cv.item]]
  	title="Asterisk"
  	rank = 5
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/asterisk.png"
   	  	
   [[cv.item]]
  	title="Kamailio"
  	rank = 3
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/kamailio.png"
   	  	
  	
   [[cv.item]]
  	title="Cisko"
  	rank = 2
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/cisco.jpg"
   	  	
  	
   [[cv.item]]
  	title="Kannel"
  	rank = 4
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/kannel.png"
   	  	
  	  	
[[cv]]
name = "WebApplication Development"
path = "WebApplication-development.html"
img="assets/images/"
  	
   [[cv.item]]
  	title="Angularjs"
  	rank = 5
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/angularjs.png"
   	  	   	  	
  	
   [[cv.item]]
  	title="Google Web Toolkit"
  	rank = 3
  	duration = 1
  	link =""	
   	extra="in production" img="assets/images/gwt.png"
   	  	
  	
   [[cv.item]]
  	title="Ruby on Rails"
  	rank = 3
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/rubyonrails.png"
   	  	
   	  	
  	
[[cv]]
name = "Cloud Computing"
path = "Cloud-computing.html"
img="assets/images/"

   [[cv.item]]
  	title="Digital Ocean"
  	rank = 5
  	duration = 1
  	link =""	
   	extra="in production" 
   	img="assets/images/digitalocean.png"
   	  	
  	
   [[cv.item]]
  	title="Amazon Web Service"
  	rank = 5
  	duration = 6
  	link ="http://aws.amazon.com/"	
   	extra="in production" 
   	img="assets/images/aws.gif"
   	
   [[cv.item]]
  	title="Google App Engine"
  	rank = 5
  	duration = 6
  	link ="https://cloud.google.com/appengine/docs/whatisgoogleappengine"	
   	extra="in production" 
   	img="assets/images/googleappengine.jpg"   	
   	  	
  	
   [[cv.item]]
  	title="Rackspace"
  	rank = 4 	  	  	
   	duration = 6
  	link =""	
   	extra="in production" 
   	img="assets/images/rackspace.png"
   	  	
  	 	   	  	 	 	  	
[[cv]]
name = "SEO Computing"
path = "Seo-computing.html"
img="assets/images/"

   [[cv.item]]
  	title="Organic optimization"
  	rank = 5
  	duration = 8
  	link =""	
   	extra="in production" 
   	img="assets/images/seo.jpg"
   	  	
  	
   [[cv.item]]
  	title="AdWords"
  	rank = 5
  	duration = 3
  	link =""	
   	extra="in production" 
   	img="assets/images/adwords.png"
   	  	
  	
   [[cv.item]]
  	title="AdSense"
  	rank = 3 	  	  	
   	duration = 3
  	link =""	
   	extra="in production" 
   	img="assets/images/adsense.png"  	
  		 			
  